
apiVersion: v1
kind: Service
metadata:
  name: ms-upload-service
spec:
  type: NodePort
  selector:
    app: ms-upload-deployment
  ports:
    - port: 80
      nodePort: 32001 
      targetPort: 3000
